var k=150,m=500,p=!0,q=6,r=1,t=50,v=!1,w=0,x=0,y=!1,z=document.documentElement,A,B=37,C=38,D=39,F=40,G=32,H=33,I=34,J=35,K=36,L=[],M=!1;
function N(a,b,c){var d;d||(d=1E3);O(b,c);L.push({x:b,y:c,a:0>b?0.99:-0.99,b:0>c?0.99:-0.99,start:+new Date});if(!M){var e=function(){for(var u=+new Date,l=0,s=0,n=0;n<L.length;n++){var f=L[n],g=u-f.start,E=g>=m,h=E?1:g/m;p&&(g=h,1<=g?h=1:0>=g?h=0:(1==r&&(r/=P(1)),h=P(g)));g=f.x*h-f.a>>0;h=f.y*h-f.b>>0;l+=g;s+=h;f.a+=g;f.b+=h;E&&(L.splice(n,1),n--)}b&&(u=a.scrollLeft,a.scrollLeft+=l,l&&a.scrollLeft===u&&(b=0));c&&(l=a.scrollTop,a.scrollTop+=s,s&&a.scrollTop===l&&(c=0));b||c||(L=[]);L.length?setTimeout(e,
d/k+1):M=!1};setTimeout(e,0);M=!0}}
function Q(a){var b=a.target,c=a.ctrlKey||a.altKey||a.metaKey;if(/input|textarea|embed/i.test(b.nodeName)||b.isContentEditable||a.defaultPrevented||c||"button"===b.nodeName.toLowerCase()&&a.keyCode===G)return!0;var d;d=b=0;var c=R(A),e=c.clientHeight;c==document.body&&(e=window.innerHeight);switch(a.keyCode){case C:d=-t;break;case F:d=t;break;case G:d=a.shiftKey?1:-1;d=-d*e*0.9;break;case H:d=0.9*-e;break;case I:d=0.9*e;break;case K:d=-c.scrollTop;break;case J:e=c.scrollHeight-c.scrollTop-e;d=0<e?
e+10:0;break;case B:b=-t;break;case D:b=t;break;default:return!0}N(c,b,d);a.preventDefault()}var S={};setInterval(function(){S={}},1E4);var T=function(){var a=0;return function(b){return b.c||(b.c=a++)}}();function U(a,b){for(var c=a.length;c--;)S[T(a[c])]=b;return b}
function R(a){var b=[],c=z.scrollHeight;do{var d=S[T(a)];if(d)return U(b,d);b.push(a);if(c===a.scrollHeight){if(!v||z.clientHeight+10<c)return U(b,document.body)}else if(a.clientHeight+10<a.scrollHeight&&(overflow=getComputedStyle(a,"").getPropertyValue("overflow"),"scroll"===overflow||"auto"===overflow))return U(b,a)}while(a=a.parentNode)}function O(a,b){a=0<a?1:-1;b=0<b?1:-1;if(w!==a||x!==b)w=a,x=b,L=[]}
function P(a){var b;a*=q;1>a?b=a-(1-Math.exp(-a)):(b=Math.exp(-1),a=1-Math.exp(-(a-1)),b+=a*(1-b));return b*r}window.addEventListener("mousedown",function(a){A=a.target},!1);
window.addEventListener("mousewheel",function(a){y||init();var b=a.target,c=R(b);if(!c||a.defaultPrevented||"embed"===A.nodeName.toLowerCase()||"embed"===b.nodeName.toLowerCase()&&/\.pdf/i.test(b.src))return!0;var b=a.wheelDeltaX||0,d=a.wheelDeltaY||0;b||d||(d=a.wheelDelta||0);1.2<Math.abs(b)&&(b*=0.6);1.2<Math.abs(d)&&(d*=0.6);N(c,-b,-d);a.preventDefault()},!1);
window.addEventListener("load",function(){if(document.body){var a=document.body,b=document.documentElement,c=window.innerHeight,d=a.scrollHeight;z=0<=document.compatMode.indexOf("CSS")?b:a;A=a;y=!0;top!=self?v=!0:d>c&&(a.offsetHeight<=c||b.offsetHeight<=c)&&(z.style.height="auto",z.offsetHeight<=c&&(b=document.createElement("div"),b.style.clear="both",a.appendChild(b)));window.addEventListener("keydown",Q,!1)}},!1);
